sudo: false
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7-dev"
install:
  - pip install .
  - pip install tox tox-travis coverage coveralls
script:
  - tox
  - coverage run ./runtests.py
  - coverage report --include=drf_batch_requests/*.py --skip-covered
  - coverage report --fail-under=80 --include=drf_batch_requests/*.py --skip-covered
after-success:
  - coveralls
