language: python
python:
  - "3.5"
  - "2.7"
  - "2.6"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install .
  - pip install nose coverage
  - pip install coveralls
script:
  - python manage.py test --settings tests.test_settings
  #- python setup.py nosetests --with-coverage --cover-package pypiview
